### ISSUE TITLE
example problem

### ISSUE THREAD

**Issue by homokia** [cesanta/slre#23]
Downloaded the code, but the "Example: find all URLs in a string" cannot find any URL in the string. And I noticed that if I make enclosed brackets in regex then it will not work.

**Comment by Snarkorel** [comment]
Looks like SLRE doesn't support (?i) metacharacter, so readme and unit tests are wrong. If you remove (?i) from regexp, it will be work fine. 

Pattern should be like this: 
regex = "((https?://)[^\\s/'\"<>]+/?[^\\s'\"<>]*)"; 
Don't forget to set SLRE_IGNORE_CASE flags in order to replace (?i) functionality.

**Comment by cpq** [comment]
That's right, (?i) is not supported.
Updated README & unit test.
Thank you @Snarkorel
